export const MOCK_WORDS = [
  { word: 'elon', weight: 0.9 },
  { word: 'musk', weight: 0.8 },
  { word: 'tesla', weight: 0.7 },
  { word: 'america', weight: 0.6 },
  { word: 'financial', weight: 0.74 },
  { word: 'crisis', weight: 0.63 },
  { word: 'iran', weight: 0.83 },
  { word: 'frank', weight: 0.34 },
  { word: 'barney', weight: 0.54 },
  { word: 'strike', weight: 0.43 },
  { word: 'school', weight: 0.38 },
  { word: 'teacher', weight: 0.53 },
  { word: 'student', weight: 0.63 },
  { word: 'class', weight: 0.73 },
  { word: 'education', weight: 0.83 },
  { word: 'learning', weight: 0.93 },
  { word: 'university', weight: 0.33 },
  { word: 'college', weight: 0.43 },
  { word: 'russia', weight: 0.53 },
  { word: 'china', weight: 0.63 },
  { word: 'japan', weight: 0.73 },
  { word: 'war', weight: 0.83 },
  { word: 'peace', weight: 0.93 },
  { word: 'nuclear', weight: 0.33 },
  { word: 'missile', weight: 0.43 },
  { word: 'weapon', weight: 0.53 },
]
